title: Rivers‘ Gallery
subtitle: Fling Beauty Eternity
description: chill in a river
cover: 'https://raw.githubusercontent.com/rivers-wqj/RiGallery/main/PKCity/IMG_4346.2mgyoj22lho0.webp'
author: Rivers

footer_logo: 
  use: self
  self:
    link: 'https://rivers-wqj.github.io/'
    src: 'https://github.com/lfkdsk/picx-images-hosting/raw/master/20230817/tripper2white.2pbuwaqvndu0.webp'

url: https://rivers-wqj.github.io/RiGallery
root: /RiGallery

photography_page:
  slogan: true
  slogan_descr: 'Lost but Tranquila in Rivers '

thumbnail_url: https://cdn.jsdelivr.net/gh/rivers-wqj/RiGallery@thumbnail/
base_url: https://cdn.jsdelivr.net/gh/rivers-wqj/RiGallery@main

nav:
  地图:
    link: /RiGallery/location
    icon: local-two
  随机:
    link: /RiGallery/random
    icon: pic
  # 查询:
  #   link: /RiGallery/query
  #   icon: history-query
  状态监控:
    link: /RiGallery/status
    icon: list-view
  时间线:
    link: /RiGallery/grid-all
    icon: grid-nine

